# Site
name: Microservices MX
# many plugins and themes expect site.title to be used instead of name
title: Microservices MX
description: Microservicios en tu idioma
meta_description: "Una fuente de contenido en español para los entusiastas en soluciones basadas con arquitectura de microservicios."
logo: 'assets/images/favicon-32x32.png'
favicon: 'assets/images/favicon.ico'
paginate: 8
baseurl: /blog
email: 'ades76mx-microservices@yahoo.com'
google_analytics: 'UA-119132347-2'
facebook_pixel: '1581831518729998'
disqus: 'microservices_mx'
sharethis: '<script async src="//platform-api.sharethis.com/js/sharethis.js#property=5bf2aa366ef16900117dd772&product="sticky-share-buttons"></script>'

# Authors
authors:
  ades:
    name: Adrian
    display_name: AdES
    gravatar: 7a2464d4f73bc942f3e8878cdfa40eca
    email: ades76mx-microservices@yahoo.com
    web: https://microservicios.com.mx
    twitter: https://twitter.com/AdES_MX
    description: "Autor en Microservicios MX, arquitecto de soluciones, su principal experiencia en desarrollo Java es en implementaciones backend como integrador de sistemas en la industria de telecomunicaciones. Es un apasionado de las nuevas tecnologías y siempre está tratando de introducir el \"estado del arte\" en sus proyectos."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-feed
#  - jekyll-seo-tag

paginate_path: "/blog/post:num/"

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/workspace.xml
  - vendor
  - node_modules

# https://github.com/jekyll/jekyll/issues/6702#issuecomment-362396126
# Collections
collections:
  workshops:
    output: true
    permalink: /:collection/:path/
  events:
    output: true
    permalink: /events/:path/
    title: Events

# Defaults
defaults:
  - scope:
      type: workshops
    values:
      layout: workshop